model_list:
  - model_name: firewall-model
    litellm_params:
      model: "openai/qwen3.5:35b-ctx100k"
      api_base: "os.environ/LITELLM_API_BASE"
      api_key: "os.environ/LITELLM_API_KEY"

litellm_settings:
  set_verbose: False
  drop_params: True

guardrails:
  - guardrail_name: "firewall"
    litellm_params:
      guardrail: litellm_content_filter
      mode: ["pre_call"]
      default_on: true
      blocked_words:
        - keyword: "Google"
          action: "BLOCK"
        - keyword: "secret@example.com"
          action: "BLOCK"
        - keyword: "Ignore instructions"
          action: "BLOCK"
